M48
; DRILL file {KiCad 7.x} date 2026-05-03
; FORMAT={-:-/ absolute / metric / suppress trailing zeros}
; #@! TF.CreationDate,2026-05-03T00:00:00+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
; #@! TF.FilePolarity,Positive
METRIC,TZ
T1C3.200
%
G90
G05
; Mounting hole M3 - NPTH 3.2mm x4
; Board: EcoSynTech V6.3 | 200x150mm
; Positions (mm): (5,5) (5,145) (195,5) (195,145)
T1
X5Y5
X5Y145
X195Y5
X195Y145
T0
M30
